Use __del__(), not __del(), in post receive hook.
This matches the prior has_attr line, and avoids an issue that looks like:

remote: Traceback (most recent call last):
remote:   File "hooks/post-receive", line 101, in <module>
remote:     git_multimail.run_as_post_receive_hook(environment, mailer)
remote:   File "/data/git/hooks/git-multimail/git-multimail/git_multimail.py", line 3472, in run_as_post_receive_hook
remote:     mailer.__del()
remote: AttributeError: 'SMTPMailer' object has no attribute '__del'

# Please enter the commit message for your changes. Lines starting
# with '#' will be ignored, and an empty message aborts the commit.
# On branch post-receive-hook-del-fix
# Changes to be committed:
#	modified:   git_multimail.py
#