change 'Errors found in:' to 'failed tests:'
so that the error message looks like:

    ERROR: failed tests: ...

instead of:

    ERROR: Errors found in: ...

(the repeated word "error" is a bit awkward)

Signed-off-by: Richard Hansen <rhansen@rhansen.org>